on:
  workflow_dispatch:
  schedule:
  - cron: "5 4 27 1,4,7,10 *"
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::tidyverse 
          any::ckanr
          any::arrow

    - run: Rscript download.R
      env:
        DATAVIC_APIKEY: ${{ secrets.DATAVIC_APIKEY }}
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Push update back to repo